# NOME DO ARQUIVO: features/business/ranking_data.py
# REFACTOR: Contém o dicionário com todos os dados das posições de ranking.

"""
Este módulo centraliza todos os dados relacionados às posições e rankings
do plano de carreira.

Manter os dados em uma estrutura isolada como esta (em vez de espalhada
pelo código) torna o bot mais fácil de atualizar e manter. Se os requisitos
de uma posição mudarem no futuro, basta alterar os valores neste dicionário.
"""

# Dicionário principal que mapeia o nome de cada posição para seus atributos.
POSITIONS = {
    "Associate": {
        "emoji": "🔹",
        "nome_curto": "A",
        "pv_mensal": 50,
        "inscritos_pessoais": 1,
        "lp_nos_3_niveis": None,
        "linhas_qualificadas": None,
        "vo_rede": None,
        "media_ganho": 233.0,
        "bonus_participacao": None,
        "viagens_incentivo": False,
        "nivel_categoria": "Início",
        "progressao_para": "Builder",
        "reconhecimento": "Pin de Associado",
        "observacao": "1 cliente preferencial ou afiliado pessoal"
    },
    "Builder": {
        "emoji": "🔸",
        "nome_curto": "B",
        "pv_mensal": 50,
        "inscritos_pessoais": 3,
        "lp_nos_3_niveis": None,
        "linhas_qualificadas": None,
        "vo_rede": None,
        "media_ganho": 490.0,
        "bonus_participacao": None,
        "viagens_incentivo": False,
        "nivel_categoria": "Construção",
        "progressao_para": "Builder Elite",
        "reconhecimento": "Pin Builder",
        "observacao": "3 inscritos pessoais com 50 PV/mês"
    },
    "Builder Elite": {
        "emoji": "🔶",
        "nome_curto": "BE",
        "pv_mensal": 50,
        "inscritos_pessoais": 3,
        "lp_nos_3_niveis": 1000,
        "linhas_qualificadas": None,
        "vo_rede": None,
        "media_ganho": 980.0,
        "bonus_participacao": None,
        "viagens_incentivo": False,
        "nivel_categoria": "Construção",
        "progressao_para": "Diamond",
        "reconhecimento": "Pin Builder Elite",
        "observacao": "3 inscritos pessoais ativos com 50 PV/mês"
    },
    "Diamond": {
        "emoji": "💎",
        "nome_curto": "D",
        "pv_mensal": 50,
        "inscritos_pessoais": 6,
        "lp_nos_3_niveis": 3000,
        "linhas_qualificadas": None,
        "vo_rede": None,
        "media_ganho": 2481.0,
        "bonus_participacao": None,
        "viagens_incentivo": False,
        "nivel_categoria": "Construção de Liderança",
        "progressao_para": "Diamond Elite",
        "reconhecimento": "Pin Diamante",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Diamond Elite": {
        "emoji": "💠",
        "nome_curto": "DE",
        "pv_mensal": 50,
        "inscritos_pessoais": 6,
        "lp_nos_3_niveis": 5000,
        "linhas_qualificadas": [{"quantidade": 2, "posicao": "Builder Elite"}],
        "vo_rede": None,
        "media_ganho": 4962.0,
        "bonus_participacao": None,
        "viagens_incentivo": False,
        "nivel_categoria": "Construção de Liderança",
        "progressao_para": "Presidential",
        "reconhecimento": "Pin Diamante Elite",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Presidential": {
        "emoji": "🏅",
        "nome_curto": "P",
        "pv_mensal": 50,
        "inscritos_pessoais": 8,
        "lp_nos_3_niveis": 10000,
        "linhas_qualificadas": [{"quantidade": 2, "posicao": "Diamond"}],
        "vo_rede": None,
        "media_ganho": 7015.0,
        "bonus_participacao": 3400.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Construção de Liderança",
        "progressao_para": "Presidential Elite",
        "reconhecimento": "Pin Presidencial + Viagens de Incentivo",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Presidential Elite": {
        "emoji": "🥇",
        "nome_curto": "PE",
        "pv_mensal": 50,
        "inscritos_pessoais": 8,
        "lp_nos_3_niveis": 15000,
        "linhas_qualificadas": [{"quantidade": 2, "posicao": "Diamond Elite"}],
        "vo_rede": None,
        "media_ganho": 14030.0,
        "bonus_participacao": 6800.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Construção de Liderança",
        "progressao_para": "Bronze",
        "reconhecimento": "Pin Presidencial Elite + Viagens",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Bronze": {
        "emoji": "🥉",
        "nome_curto": "Bz",
        "pv_mensal": 50,
        "inscritos_pessoais": 10,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 2, "posicao": "Presidential"}],
        "vo_rede": None,
        "media_ganho": 28493.0,
        "bonus_participacao": 13600.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Liderança",
        "progressao_para": "Bronze Elite",
        "reconhecimento": "Pin Bronze + Viagens",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Bronze Elite": {
        "emoji": "🏆",
        "nome_curto": "BzE",
        "pv_mensal": 50,
        "inscritos_pessoais": 10,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Presidential"}],
        "vo_rede": 50000.0,
        "media_ganho": 56986.0,
        "bonus_participacao": 27200.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Liderança",
        "progressao_para": "Silver",
        "reconhecimento": "Pin Bronze Elite + Viagens",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Silver": {
        "emoji": "🥈",
        "nome_curto": "S",
        "pv_mensal": 50,
        "inscritos_pessoais": 10,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Presidential Elite"}],
        "vo_rede": 100000.0,
        "media_ganho": 63527.0,
        "bonus_participacao": 54400.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Liderança",
        "progressao_para": "Silver Elite",
        "reconhecimento": "Pin Prata + Viagens",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Silver Elite": {
        "emoji": "🌟",
        "nome_curto": "SE",
        "pv_mensal": 50,
        "inscritos_pessoais": 10,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Bronze"}],
        "vo_rede": 175000.0,
        "media_ganho": 95291.0,
        "bonus_participacao": 108800.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Liderança",
        "progressao_para": "Gold",
        "reconhecimento": "Pin Prata Elite + Viagens",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Gold": {
        "emoji": "🥇",
        "nome_curto": "G",
        "pv_mensal": 50,
        "inscritos_pessoais": 12,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Silver"}],
        "vo_rede": 250000.0,
        "media_ganho": 154261.0,
        "bonus_participacao": 178000.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Liberdade Financeira",
        "progressao_para": "Gold Elite",
        "reconhecimento": "Pin Ouro + Dividendos",
        "observacao": "Necessário já ter qualificado como Silver Elite pelo menos uma vez"
    },
    "Gold Elite": {
        "emoji": "🏆",
        "nome_curto": "GE",
        "pv_mensal": 50,
        "inscritos_pessoais": 12,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Gold"}],
        "vo_rede": 500000.0,
        "media_ganho": 308522.0,
        "bonus_participacao": 356000.0,
        "viagens_incentivo": True,
        "nivel_categoria": "Liberdade Financeira",
        "progressao_para": "Platinum",
        "reconhecimento": "Pin Ouro Elite + Dividendos",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Platinum": {
        "emoji": "💍",
        "nome_curto": "Ptm",
        "pv_mensal": 50,
        "inscritos_pessoais": 12,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Gold Elite"}],
        "vo_rede": 1000000.0,
        "media_ganho": 782086.0,
        "bonus_participacao": None,
        "viagens_incentivo": True,
        "nivel_categoria": "Topo da Carreira",
        "progressao_para": "Platinum Elite",
        "reconhecimento": "Pin Platina + Prestígio Internacional",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    },
    "Platinum Elite": {
        "emoji": "👑",
        "nome_curto": "PtmE",
        "pv_mensal": 50,
        "inscritos_pessoais": 12,
        "lp_nos_3_niveis": 20000,
        "linhas_qualificadas": [{"quantidade": 3, "posicao": "Platinum"}],
        "vo_rede": 2000000.0,
        "media_ganho": 1564172.0,
        "bonus_participacao": None,
        "viagens_incentivo": True,
        "nivel_categoria": "Topo da Carreira",
        "progressao_para": None,
        "reconhecimento": "Pin Platina Elite + Prestígio Internacional",
        "observacao": "Metade dos inscritos deve estar na linha de frente"
    }
}